apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-app
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-app
    spec:
      containers:
        - name: {{ .Chart.Name }}-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            - containerPort: 8000
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          #livenessProbe:
           # tcpSocket:
            #  port: {{ .Values.probes.liveness.port }}
            #initialDelaySeconds: 5
            #periodSeconds: 10

          readinessProbe:
            tcpSocket:
              port: {{ .Values.probes.readiness.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
